Repository k0msenapati/study-sphere, pull requests merged in 2025-08, with the labels that each got.

#160 Fix: Ensure hover effect keeps text visible and improves background a…
  src/components/landing/HeroSection.tsx
  src/components/landing/LandingNavbar.tsx
Labels: Beginner, SSoC25

#163 Added the Bookmark feature for Notes section
  drizzle/0006_tranquil_the_initiative.sql
  drizzle/meta/0006_snapshot.json
  drizzle/meta/_journal.json
  drizzle/relations.ts
  drizzle/schema.ts
  src/app/api/notes/bookmarks/route.ts
  src/app/dashboard/notes/page.tsx
  src/lib/db/schema.ts
  src/lib/notes/types.ts
  src/lib/notes/use-notes.ts
Labels: Intermediate, SSoC25

#169 Google recaptcha
  .env.example
  README.md
  package-lock.json
  package.json
  src/app/api/auth/login/route.ts
  src/app/api/auth/register/route.ts
  src/components/auth/Login.tsx
  src/components/auth/Register.tsx
  src/lib/auth/recaptcha.ts
Labels: Advanced, SSoC25

#173 Fixed navbar status according to authentication
  src/app/page.tsx
  src/components/landing/LandingNavbar.tsx
Labels: Beginner, SSoC25

#171 Fixed spelling mistake
  .github/pull_request_template.md
Labels: Beginner, SSoC25
